package org.aethercode.orchestration.plan;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * GoalAct-style global plan that is continuously updated.
 * <p>
 * Paper: 2504.16563 GoalAct (清华). Each time step, the plan is re-generated by
 * policy {@code pi(query, tools, history) -> next plan}. The last step is always
 * designated as {@link Skill#FINISH}.
 * <p>
 * Differences from {@code DagPlan}:
 * <ul>
 *   <li>{@code GlobalPlan} is meant to be re-generated each step (re-planning),
 *       not pre-built upfront.</li>
 *   <li>Each step carries a {@link Skill} enum (searching / coding / writing /
 *       reasoning / finish) rather than raw tool calls.</li>
 *   <li>The terminal step is always FINISH (cannot be skipped).</li>
 * </ul>
 */
public final class GlobalPlan {

    /** High-level skill that one plan step delegates to. */
    public enum Skill {
        SEARCHING,
        CODING,
        WRITING,
        REASONING,
        RESEARCH,
        FINISH
    }

    /** One plan step: a (plan description, skill) pair. */
    public record Step(String id, String description, Skill skill) {
        public Step {
            if (id == null || id.isBlank()) {
                id = UUID.randomUUID().toString();
            }
            Objects.requireNonNull(skill, "skill");
        }
    }

    private final List<Step> steps;

    private GlobalPlan(List<Step> steps) {
        this.steps = List.copyOf(steps);
    }

    public static GlobalPlan of(List<Step> steps) {
        Objects.requireNonNull(steps, "steps");
        if (steps.isEmpty()) {
            throw new IllegalArgumentException("plan must have at least one step");
        }
        if (steps.get(steps.size() - 1).skill() != Skill.FINISH) {
            throw new IllegalArgumentException("last step must be FINISH");
        }
        return new GlobalPlan(steps);
    }

    public static GlobalPlan ofSingle(Skill skill, String description) {
        return of(List.of(new Step(null, description, skill)));
    }

    public static GlobalPlan ofSequence(Skill... skills) {
        if (skills == null || skills.length == 0) {
            throw new IllegalArgumentException("at least one skill required");
        }
        List<Step> list = new ArrayList<>(skills.length);
        for (int i = 0; i < skills.length; i++) {
            Skill s = skills[i];
            String desc = "step " + (i + 1) + ": " + s.name().toLowerCase();
            list.add(new Step(null, desc, s));
        }
        return of(list);
    }

    public List<Step> steps() {
        return steps;
    }

    public int size() {
        return steps.size();
    }

    public Step first() {
        return steps.get(0);
    }

    public Step last() {
        return steps.get(steps.size() - 1);
    }

    public boolean isFinished() {
        return steps.size() == 1 && last().skill() == Skill.FINISH;
    }

    /**
     * Update the plan (GoalAct style re-planning).
     * <p>
     * Returns a new plan; the original is not mutated.
     *
     * @param newSteps the new step list (must end with FINISH)
     */
    public GlobalPlan update(List<Step> newSteps) {
        return of(newSteps);
    }

    /** Drop the first step (advance). Used after the agent executed the first step. */
    public GlobalPlan advance() {
        if (steps.size() == 1) {
            return this;
        }
        return of(steps.subList(1, steps.size()));
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GlobalPlan{");
        for (int i = 0; i < steps.size(); i++) {
            if (i > 0) sb.append(" -> ");
            sb.append(steps.get(i).skill().name());
        }
        sb.append("}");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof GlobalPlan other)) return false;
        return steps.equals(other.steps);
    }

    @Override
    public int hashCode() {
        return steps.hashCode();
    }
}
