// Phase 4.1 (T-4-03): SessionListRow.
//
// One row in the virtual session list. Visual model:
//
//   ┌──────────────────────────────────────────────┐
//   │ ●  Fix Cwe252 unchecked return              │
//   │   /Users/me/proj/fathom-dfa · 2h · 12 msg    │
//   │   "fathom-dfa ... R437 验证 取消"   4.2K tok  │
//   └──────────────────────────────────────────────┘
//
// Five fields:
//   - title (auto-generated by the daemon or set via rename)
//   - cwd (one-line, ellipsised)
//   - lastActiveAt (relative — "3h ago")
//   - preview (first user message, capped at 200 chars by the daemon)
//   - token total (input + output)
//
// The "current" row gets a coloured stripe + brighter text.
// The row is clickable; the parent's `onSelect` fires on
// activation (Enter / click). A delete button is hidden on
// the active row (the daemon refuses to delete the current
// session) but visible on hover for the others.
//
// title resolution. Previously the fallback was
// "Session <id-suffix>" which the user called 难以辨认
// (unclear / unrecognisable). They asked for one of three:
//   - <未命名> (Unnamed) for sessions with no message yet
//   - the first prompt (preview) as the title once a
//     user message exists
//   - optionally an LLM-generated title in a future round
//     (out of scope for R204 — the preview is the
//     pragmatic source of truth; the daemon's first user
//     message is the only thing we KNOW about the
//     session's intent).
// We use the preview as the title, truncated to 60 chars
// to keep the row tight. The session id is still in the
// tooltip (browser native) for power users.

import { useMemo, type CSSProperties } from 'react';
import type { SessionListItem } from '../../rpc/types';

export interface SessionListRowProps {
  session: SessionListItem;
  isCurrent: boolean;
  isStreaming?: boolean;
  onSelect: (id: string) => void;
  onDelete?: (id: string) => void;
  /** Style spread from the parent (absolute positioning). */
  style?: CSSProperties;
  /** Tab index override (default 0). */
  tabIndex?: number;
}

function formatLastActive(ts?: number): string {
  if (!ts) return '—';
  const now = Date.now();
  const dt = now - ts;
  if (dt < 60_000) return 'just now';
  if (dt < 3_600_000) return `${Math.floor(dt / 60_000)}m`;
  if (dt < 86_400_000) return `${Math.floor(dt / 3_600_000)}h`;
  return `${Math.floor(dt / 86_400_000)}d`;
}

function ellipsisePath(p: string, max: number): string {
  if (p.length <= max) return p;
  return p.slice(0, max - 1) + '…';
}

function formatTokens(n?: number): string {
  if (n == null) return '—';
  if (n < 1000) return String(n);
  if (n < 1_000_000) return `${(n / 1000).toFixed(1)}k`;
  return `${(n / 1_000_000).toFixed(2)}M`;
}

function sessionDisplayTitle(s: SessionListItem): string {
  // title fallback chain. The user asked for
  // a clear name instead of the cryptic session id
  // suffix. The chain:
  //   1. Explicit title (daemon or user-renamed)
  //   2. The first user prompt (preview) — this is
  //      the most reliable signal of "what is this
  //      session about" since the daemon extracts
  //      it from the first assistant-bound message
  //   3. <未命名> (Unnamed) — a session with no message yet
  //      is genuinely unnamed; the user knows it's
  //      a brand-new session by the empty preview
  //      and the lack of any other content. Showing
  //      "Session <id-suffix>" was unhelpful because
  //      the suffix is just a UUID tail.
  //
  // Future round: hook an LLM to summarise the first
  // message into a shorter, more "title-y" string.
  // Out of scope for R204 — the user said the title
  // "Can be LLM-generated" — so the preview is a good
  // intermediate state.
  if (s.title && s.title.trim()) return s.title;
  if (s.preview && s.preview.trim()) {
    const p = s.preview.trim();
    return p.length > 60 ? p.slice(0, 57) + '...' : p;
  }
  return '未命名';
}

export function SessionListRow({
  session,
  isCurrent,
  isStreaming = false,
  onSelect,
  onDelete,
  style,
  tabIndex = 0,
}: SessionListRowProps) {
  const title = useMemo(() => sessionDisplayTitle(session), [session]);
  const lastActive = useMemo(() => formatLastActive(session.lastActiveAt), [session.lastActiveAt]);
  const cwd = useMemo(() => ellipsisePath(session.cwd ?? '', 36), [session.cwd]);
  const totalTokens = useMemo(
    () => (session.tokensIn ?? 0) + (session.tokensOut ?? 0),
    [session.tokensIn, session.tokensOut],
  );
  const isStale = !isCurrent && (session.lastActiveAt ?? 0) < Date.now() - 3_600_000;

  return (
    <div
      className={[
        'session-list-row',
        isCurrent ? 'session-list-row-current' : '',
        isStreaming ? 'session-list-row-streaming' : '',
        isStale ? 'session-list-row-stale' : '',
      ].filter(Boolean).join(' ')}
      style={style}
      role="option"
      aria-selected={isCurrent}
      tabIndex={tabIndex}
      onClick={() => onSelect(session.id)}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(session.id);
        }
      }}
      title={`${session.id}\n${session.cwd ?? ''}\nlast active ${lastActive}`}
    >
      <span
        className={[
          'session-list-row-dot',
          isCurrent ? (isStreaming ? 'session-list-row-dot-active' : 'session-list-row-dot-current') : '',
          isStale ? 'session-list-row-dot-stale' : '',
        ].filter(Boolean).join(' ')}
        aria-hidden
      />
      <div className="session-list-row-body">
        <div className="session-list-row-title">{title}</div>
        <div className="session-list-row-meta">
          <span className="session-list-row-cwd">{cwd || '—'}</span>
          <span className="session-list-row-sep" aria-hidden>·</span>
          <span className="session-list-row-when">{lastActive}</span>
          {totalTokens > 0 && (
            <>
              <span className="session-list-row-sep" aria-hidden>·</span>
              <span className="session-list-row-tokens">{formatTokens(totalTokens)} tok</span>
            </>
          )}
        </div>
        {session.preview && (
          <div className="session-list-row-preview">"{session.preview}"</div>
        )}
      </div>
      {!isCurrent && onDelete && (
        <button
          className="session-list-row-delete"
          title="Delete this session"
          aria-label={`Delete session ${title}`}
          onClick={(e) => {
            e.stopPropagation();
            onDelete(session.id);
          }}
        >×</button>
      )}
    </div>
  );
}
