package org.aethercode.orchestration.plan;

import org.aethercode.orchestration.plan.GlobalPlan.Skill;
import org.aethercode.orchestration.plan.GlobalPlan.Step;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class GlobalPlanTest {

    @Test
    void singleStepPlanIsFinished() {
        GlobalPlan plan = GlobalPlan.ofSingle(Skill.FINISH, "done");
        assertEquals(1, plan.size());
        assertTrue(plan.isFinished());
        assertEquals(Skill.FINISH, plan.last().skill());
    }

    @Test
    void multiStepPlanMustEndWithFinish() {
        GlobalPlan plan = GlobalPlan.ofSequence(Skill.SEARCHING, Skill.WRITING, Skill.FINISH);
        assertEquals(3, plan.size());
        assertEquals(Skill.SEARCHING, plan.first().skill());
        assertEquals(Skill.FINISH, plan.last().skill());
        assertFalse(plan.isFinished());
    }

    @Test
    void emptyPlanRejected() {
        assertThrows(IllegalArgumentException.class, () -> GlobalPlan.of(List.of()));
    }

    @Test
    void nonFinishLastRejected() {
        Step s1 = new Step(null, "search", Skill.SEARCHING);
        Step s2 = new Step(null, "write", Skill.WRITING);
        assertThrows(IllegalArgumentException.class, () -> GlobalPlan.of(List.of(s1, s2)));
    }

    @Test
    void updateReplacesSteps() {
        GlobalPlan p1 = GlobalPlan.ofSequence(Skill.SEARCHING, Skill.FINISH);
        Step new1 = new Step(null, "now research", Skill.RESEARCH);
        Step new2 = new Step(null, "finish", Skill.FINISH);
        GlobalPlan p2 = p1.update(List.of(new1, new2));
        assertNotEquals(p1, p2);
        assertEquals(Skill.RESEARCH, p2.first().skill());
        assertEquals(2, p2.size());
    }

    @Test
    void advanceDropsFirstStep() {
        GlobalPlan p1 = GlobalPlan.ofSequence(Skill.SEARCHING, Skill.WRITING, Skill.FINISH);
        GlobalPlan p2 = p1.advance();
        assertEquals(2, p2.size());
        assertEquals(Skill.WRITING, p2.first().skill());
    }

    @Test
    void advanceSingleStepReturnsSame() {
        GlobalPlan p1 = GlobalPlan.ofSingle(Skill.FINISH, "done");
        GlobalPlan p2 = p1.advance();
        assertEquals(p1, p2);
        assertTrue(p2.isFinished());
    }

    @Test
    void autoGeneratedStepId() {
        Step s = new Step(null, "x", Skill.SEARCHING);
        assertNotNull(s.id());
        assertFalse(s.id().isBlank());

        Step s2 = new Step("my-id", "y", Skill.CODING);
        assertEquals("my-id", s2.id());
    }

    @Test
    void hierarchicalExecutorDispatches() {
        HierarchicalExecutor ex = HierarchicalExecutor.builder()
            .searching(step -> "search-result:" + step.description())
            .coding(step -> "code-result:" + step.description())
            .finish(step -> "DONE")
            .build();

        GlobalPlan plan = GlobalPlan.ofSequence(Skill.SEARCHING, Skill.CODING, Skill.FINISH);
        String out = ex.executeAll(plan);
        assertTrue(out.contains("search-result"));
        assertTrue(out.contains("code-result"));
        assertTrue(out.contains("DONE"));
    }

    @Test
    void hierarchicalExecutorSwitchBySkill() {
        HierarchicalExecutor ex = HierarchicalExecutor.builder().build();
        Step searchStep = new Step(null, "find x", Skill.SEARCHING);
        Step writeStep = new Step(null, "summarize", Skill.WRITING);
        Step finishStep = new Step(null, "done", Skill.FINISH);
        assertTrue(ex.execute(searchStep).startsWith("search:"));
        assertTrue(ex.execute(writeStep).startsWith("write:"));
        assertEquals("OK", ex.execute(finishStep));
    }
}
